package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_compile")

py_proto_compile(
	name = "protos",
	protos = [
		"core.protos"],
	verbose = 1,
)
